### ISSUE TITLE
Error: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by apentinen** [emc-openstack/unity-cinder-driver#1]
Got above error when tried to integrate EMC Unity cinder driver with TripleO Openstack Newton release.

Workarounded it by adding:
import ssl
and in EMCUnityRESTClient class __init__:
ssl._create_default_https_context = ssl._create_unverified_context
as was suggested here:
https://github.com/servo/servo/issues/5917

EMC Unity backend: UnityOE V4.0

Error details:
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume Traceback (most recent call last):
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/cmd/volume.py", line 99, in main
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     cluster=cluster)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/service.py", line 382, in create
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     cluster=cluster)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/service.py", line 202, in __init__
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     *args, **kwargs)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 242, in __init__
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     active_backend_id=curr_active_backend_id)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 44, in import_object
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     return import_class(import_str)(*args, **kwargs)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/emc_unity.py", line 1455, in __init__
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     self.helper = EMCUnityHelper(self.configuration)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/emc_unity.py", line 639, in __init__
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     ('name', 'softwareVersion'))
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/emc_unity.py", line 314, in get_basic_syste
m_info
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     return self._get_all('basicSystemInfo', fields)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/emc_unity.py", line 283, in _get_all
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     err, resp = self._request(get_all_url)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/emc_unity.py", line 201, in _request
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     err, resp = self._send_request(req)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/emc/emc_unity.py", line 216, in _send_request
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     resp = self.url_opener.open(req)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib64/python2.7/urllib2.py", line 431, in open
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     response = self._open(req, data)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     '_open', req)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     result = func(*args)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     context=self._context, check_hostname=self._check_hostname)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume   File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume     raise URLError(err)
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)>
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.138 179185 ERROR cinder.cmd.volume
Nov 17 12:36:00 localhost cinder-volume: 2016-11-17 12:36:00.142 179185 ERROR cinder.cmd.volume [req-f2ec8f11-a69e-45fd-8566-1356d4135822 - - - - -] No volume service(s) started successfully, terminating.
Nov 17 12:36:04 localhost cinder-volume: 2016-11-17 12:36:04.369 179205 ERROR cinder.cmd.volume [req-83747495-b71e-4c3c-a59a-e8023f9440be - - - - -] Volume service overcloud-controller-0@unity failed to sta
rt.

**Comment by peter-wangxu** [comment]
Hi @apentinen

This is a known issue for old Unity cinder driver if Python version is newer than `2.7.9`
We have fixed the ssl issue in:
https://review.openstack.org/#/c/396477/

Cloud you please give a try on it?
you can download it via git command: `git fetch https://git.openstack.org/openstack/cinder refs/changes/77/396477/4 && git checkout FETCH_HEAD`

**Comment by denny-zhao** [comment]
Note that the version @peter-wangxu mentioned in last comment is still in code review on upstream. Although is not merged yet, it is fully functioning and well tested. Ocata release is the first OpenStack official release that contains Unity Cinder driver. The driver also works well for Newton. Before loading the new driver, please install python lib `storops` from pypi.

**Comment by apentinen** [comment]
Thanks!

New driver works fine.

Btw. issue above is visible also with older python versions:
[heat-admin@overcloud-controller-0 ~]$ python --version
Python 2.7.5

**Comment by nathharp** [comment]
Any chance of some further input into how to get this new driver up and running?

**Comment by peter-wangxu** [comment]
@nathharp the Unity driver will be included in the upcoming `Ocata` release, you can refer to [this doc](http://docs-draft.openstack.org/56/422456/18/check/gate-openstack-manuals-tox-doc-publish-checkbuild/176fdc1//publish-docs/draft/config-reference/block-storage/drivers/dell-emc-unity-driver.html) if you want to try devstack with latest Unity cinder driver.

Let me know if it is applicable for you.

Thanks
Peter

**Comment by nathharp** [comment]
@peter-wangxu I between supported versions - I have a staging system running Netwon at the moment, but it's not really appropriate to run devstack for that system.  

I have used the suggested workaround for now, and I guess I will have to wait for the full Ocata release when it comes.

**Comment by peter-wangxu** [comment]
@apentinen @nathharp newton branch is ready for use now.
https://github.com/emc-openstack/unity-cinder-driver/tree/newton

**Comment by fsmed** [comment]
@peter-wangxu I'm still getting this ssl certificate error with 0.4.3 Mitaka release and python 2.7.12. Will be going to Newton soon (waiting for another plugin to support it) but would be nice if I got this working before that, any ideas?

**Comment by peter-wangxu** [comment]
@Hiki- Did you follow the https://github.com/emc-openstack/unity-cinder-driver/tree/mitaka#driver-configuration to configure the driver correctly?

Basically, you will need to install `storops` and change the `volume_driver` value for the mitaka driver.

Thanks
Peter

**Comment by fsmed** [comment]
@peter-wangxu 

Current config:
```
[DEFAULT]`
...
enable_backends = unity

[unity]
## Storage protocol
storage_protocol = iSCSI
## Storage pool which the backend is going to manage
storage_pool_names = Thu Pool-01
## Unisphere IP
san_ip = 10.80.26.11
## Unisphere username and password
san_login = Local/openstack
san_password = ...
## Volume driver name
volume_driver = cinder.volume.drivers.emc.emc_unity.EMCUnityDriver
## backend's name
volume_backend_name = Storage_ISCSI_01
## unity ports
unity_io_ports = *_eth5
```

cinder-volume now logs:
`INFO cinder.volume.manager [req-7e6e05e3-7544-41f5-8cd0-59a991af3cb0 - - - - -] Starting volume driver LVMVolumeDriver (3.0.0)`

# pip  search storops
storops (0.4.11)  - Python API for VNX and Unity.
  INSTALLED: 0.4.11 (latest)
# python --version
Python 2.7.12

When it was working with Ubuntu 14.04 I had this configuration:
```
[DEFAULT]`
....
## Storage protocol
storage_protocol = iSCSI
## Storage pool which the backend is going to manage
storage_pool_names = Thu Pool-01
## Unisphere IP
san_ip = 10.80.26.11
## Unisphere username and password
san_login = Local/openstack
san_password = ...
## Volume driver name
volume_driver = cinder.volume.drivers.emc.emc_unity.EMCUnityDriver
## backend's name
volume_backend_name = Storage_ISCSI_01
## unity ports
unity_io_ports = *_eth5
```


When I use this now I get these logs:
```
2017-04-10 13:15:35.645 14616 INFO root [-] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
2017-04-10 13:15:35.679 14616 INFO root [-] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
2017-04-10 13:15:35.740 14616 WARNING py.warnings [req-a9e4496c-aa59-46b4-8e05-00aa6feeb716 - - - - -] /usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/enginefacade.py:241: NotSupportedWarning: Configuration option(s) ['use_tpool'] not supported
  exception.NotSupportedWarning

2017-04-10 13:15:35.863 14616 INFO cinder.rpc [req-a9e4496c-aa59-46b4-8e05-00aa6feeb716 - - - - -] Automatically selected cinder-scheduler objects version 1.3 as minimum service version.
2017-04-10 13:15:35.869 14616 INFO cinder.rpc [req-a9e4496c-aa59-46b4-8e05-00aa6feeb716 - - - - -] Automatically selected cinder-scheduler RPC version 2.0 as minimum service version.
2017-04-10 13:15:35.919 14616 INFO cinder.volume.manager [req-a9e4496c-aa59-46b4-8e05-00aa6feeb716 - - - - -] Determined volume DB was not empty at startup.
2017-04-10 13:15:35.970 14616 CRITICAL cinder [req-a9e4496c-aa59-46b4-8e05-00aa6feeb716 - - - - -] URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
2017-04-10 13:15:35.970 14616 ERROR cinder Traceback (most recent call last):
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/bin/cinder-volume", line 10, in <module>
2017-04-10 13:15:35.970 14616 ERROR cinder     sys.exit(main())
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/cmd/volume.py", line 93, in main
2017-04-10 13:15:35.970 14616 ERROR cinder     server = service.Service.create(binary='cinder-volume')
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/service.py", line 268, in create
2017-04-10 13:15:35.970 14616 ERROR cinder     service_name=service_name)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/service.py", line 150, in __init__
2017-04-10 13:15:35.970 14616 ERROR cinder     *args, **kwargs)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 284, in __init__
2017-04-10 13:15:35.970 14616 ERROR cinder     active_backend_id=curr_active_backend_id)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/oslo_utils/importutils.py", line 44, in import_object
2017-04-10 13:15:35.970 14616 ERROR cinder     return import_class(import_str)(*args, **kwargs)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_unity.py", line 1459, in __init__
2017-04-10 13:15:35.970 14616 ERROR cinder     self.helper = EMCUnityHelper(self.configuration)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_unity.py", line 643, in __init__
2017-04-10 13:15:35.970 14616 ERROR cinder     ('name', 'softwareVersion'))
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_unity.py", line 318, in get_basic_system_info
2017-04-10 13:15:35.970 14616 ERROR cinder     return self._get_all('basicSystemInfo', fields)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_unity.py", line 287, in _get_all
2017-04-10 13:15:35.970 14616 ERROR cinder     err, resp = self._request(get_all_url)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_unity.py", line 205, in _request
2017-04-10 13:15:35.970 14616 ERROR cinder     err, resp = self._send_request(req)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/emc/emc_unity.py", line 220, in _send_request
2017-04-10 13:15:35.970 14616 ERROR cinder     resp = self.url_opener.open(req)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/urllib2.py", line 429, in open
2017-04-10 13:15:35.970 14616 ERROR cinder     response = self._open(req, data)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
2017-04-10 13:15:35.970 14616 ERROR cinder     '_open', req)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
2017-04-10 13:15:35.970 14616 ERROR cinder     result = func(*args)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
2017-04-10 13:15:35.970 14616 ERROR cinder     context=self._context)
2017-04-10 13:15:35.970 14616 ERROR cinder   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
2017-04-10 13:15:35.970 14616 ERROR cinder     raise URLError(err)
2017-04-10 13:15:35.970 14616 ERROR cinder URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

```

EDIT: Spotted the volume driver name difference, works now, thanks!

**Comment by peter-wangxu** [comment]
Glad to see it is working now.

I guess you changed the `volume_driver` to `cinder.volume.drivers.dell_emc.unity.Driver` 

BTW, you have a typo under the `[DEFAULT]`, it's `enabled_backends` not `enable_backends`

Thanks
Peter
